export default function Chapitre3() {
    return (<div style={{maxWidth:"600px", textAlign:"justify"}}>
<h2>Chapitre 3 : La fête nationale</h2>
<br></br>
<p>
&nbsp;&nbsp;Cela faisait plus d'une semaine qu'il y avait eu l'évasion à la maison centrale. Le criminel n'avait toujours pas été retrouvé. Le bon sens voulait qu'il ne soit pas resté à Saint-Maur pour se cacher, mais qu'il se soit enfui le plus loin possible pour semer la police qui était à sa recherche. C'était la pensée que partageaient la plupart des habitants de la commune, si bien que la crainte générale qui s'était manifestée le premier jour commençait à se dissiper. 
<br></br>&nbsp;&nbsp;La véritable menace était la chaleur qui était de plus en plus torride. Les gens restaient enfermés chez eux, les volets clos, en attendant désespérément la nuit. Et même si la température redescendait le soir, elle restait élevée. La fête nationale qui avait lieu au milieu du mois menaçait d'être annulée, car le risque que représentaient les feux d'artifices avec un tel niveau de sécheresse était trop important. 
<br></br>&nbsp;&nbsp;Les trois filles souffraient de la chaleur comme toutes les autres personnes. Elles préfèraient rester dans leur chambre ventilée ou climatisée, plutôt que d'aller affronter la fournaise que même la fraîcheur de la rivière ne pouvait atténuer. 
<br></br>&nbsp;&nbsp;Lou avait complètement mis de côté la règle qu'elle avait imposée de ne parler au <i>tolkiwolki</i> qu'en cas d'urgence, et elle était la plus à même d'initier une conversation depuis sa chambre. Il faut dire que depuis leur balade à vélo et ce qu'elles avaient vues, les petites avaient beaucoup de choses à dire. Elles avaient chacune des hypothèses sur la mystérieuse abscence des yeux sur les deux animaux, et ne parvenaient pas à se mettre d'accord. 
<br></br>&nbsp;&nbsp;"Je suis sure que c'est des oiseaux qui ont fait ça, certifiait Norah.
<br></br>- Mais un oiseau ne se contente pas de prendre juste les yeux ! répondait Margaux. Déjà moi je pense que c'est une coïncidence, et que le poisson et l'oiseau ont perdu leurs yeux pour des raisons différentes.
<br></br>- Ce n'est pas possible, dit Lou. C'est trop étrange pour que ce ne soit pas lié. Mais je suis d'accord avec toi et je doute fort que ce soit à cause d'un oiseau ou un autre animal. 
<br></br>- Et si c'était une maladie ? Qui fait perdre leurs yeux aux animaux ? suggéra Norah.
<br></br>- Beurk ! J'espère qu'elle ne se transmet pas aux humains ! s'exclama Margaux avec écoeurement. En plus Lou, tu as été éclaboussée par de l'eau qui a été contaminée par le poisson, fit-elle remarquer. Lou douta un court instant, puis répondit d'un air circonspect :
<br></br>- Une maladie qui touche à la fois les poissons et les oiseaux ? Ça serait étonnant, alors encore moins de chance qu'elle se transmette aux humains. Et puis je me suis douchée juste après !
<br></br>- C'était peut être trop tard... murmura Norah.
<br></br>- Ha non ! s'aggaça Lou. Puisque je vous dit que ça ne peut pas être une maladie ! Vous savez quoi ? Je suis certaine que c'est l'évadé qui a fait ça. C'est un criminel après tout, il fait des trucs de criminel.
<br></br>- N'importe quoi, s'indigna Margaux. L'évadé a dû s'enfuir loin d'ici, il ne va tout de même pas rester dans la même ville que la prison d'où il s'est échappé.
<br></br>- C'est peut être parce que ça semble évident qu'il ne l'a pas fait, rétorqua Lou. Bon de toute façon j'ai bientôt plus de piles moi, il faut que je vous laisse."
<br></br>&nbsp;&nbsp;Ces évènements faisaient travailler leur imagination et elles formulaient de nouvelles idées chaque jour, sans en trouver qui soit réellement convaincante. 
<br></br>
<br></br>&nbsp;&nbsp;Comme pour contrebalancer l'effet négatif qu'avait suscité l'évasion sur les habitants de Saint-Maur, la météo fût clémente la veille de la fête nationale. Il plut un peu, juste assez pour rafraîchir l'atsmosphère et réhumidifier la végétation qui menaçait de partir en fumée à cause de la sécheresse. Le feu d'artifice était maintenu. Il aurait lieu dans la prairie au milieu de Saint-Maur, un grand espace vert dégagé bien connu des promeneurs.
<br></br>&nbsp;&nbsp;Lou, Margaux et Norah devaient se retrouver à cette occasion. Elles avaient prévu de faire du vélo avant d'aller s'installer dans la prairie avec leurs parents pour assister au spectacle pyrotechnique. Il était aux alentours de 21h, et comme le ciel était légèrement voilé, la lumière du crépuscule paraissait plus sombre. 
<br></br>&nbsp;&nbsp;Lou pédalait sur son vélo pour aller retrouver Norah à l'étang des Ballastières. Margaux devait les rejoindre plus tard, un peu avant le feu d'artifice. 
<br></br>&nbsp;&nbsp;L'endroit du rendez-vous n'était pas anodin : depuis qu'elles avaient vu les animaux morts dépouvus d'yeux, elles n'avaient pas eu l'occasion de retourner à l'étang. Comme cette histoire avait occupé leur esprit depuis, sans qu'elles puissent y trouver une explication, elles s'étaient mises d'accord sur le fait que les réponses devaient se trouver sur place. 
<br></br>&nbsp;&nbsp;Arrivée non loin de l'endroit où la mère de Norah était restée discuter, Lou saisit son <i>toki</i> et essaya de communiquer avec Norah. Malgré plusieurs tentatives, elle n'eut pas de réponse. Lou grommela et marcha jusqu'à un muret sur lequel elle s'assit pour attendre son amie. Il y avait quelques personnes qui passaient, la plupart pour patienter avant le feu d'artifice. Lou avait recontacté Norah plusieurs fois, en vain, et elle commençait à s'impatienter. 
<br></br>&nbsp;&nbsp;En face d'elle, elle pouvait voir la surface calme de l'étang qui reflétait le ciel teinté d'un bleu sombre et metallique et d'un orange passé. Elle décida de s'avancer au bord de l'eau pour y jeter des cailloux. Elle laissa son vélo à côté du muret et marcha un peu pour s'avancer sur la berge. Elle avait ramassé quelques pierres, et les lançait les unes après les autres. Elles faisaient un "plouf" bref quelques mètres plus loin, et Lou regardait la surface de l'eau se rétablir peu à peu après que les ondes se soient propagées en grossissant et mourant à la fois.
<br></br>&nbsp;&nbsp;Quelque chose attira son attention. Sur un îlot non loin d'elle, elle aperçu une silhouette qui bougeait derrière les arbres. Son coeur commença à battre plus fort, et instinctivement, bien qu'elle fût séparée de l'îlot par l'eau de l'étang, elle fit deux pas en arrière. Après quelques secondes, elle vit la silhouette s'avançer et sortir de derrière la végétation, et ce qu'elle vit la rassura. 
<br></br>&nbsp;&nbsp;C'était un héron, ou plus exactement, le héron de l'étang. Cet échassier à l'allure élegante et somptueuse, régnait sur l'étang et la prairie depuis de nombreuses années, et on pouvait apercevoir cet oiseau souverain les rares fois où il sortait dans son royaume.  
<br></br>&nbsp;&nbsp;Lou ne l'avait vu qu'une ou deux fois auparavant, et elle se sentit remplie d'un sentiment d'émerveillement. Le grand oiseau tronait sur un arbre mort légèrement submergé et il restait immobile. Puis après quelques instants, il tourna la tête d'un côté, puis de l'autre, puis s'avança en déployant ses ailes et en fléchissant ses pattes. Il donna une impulsion qui le propulsa dans les airs, et après quelques battements d'ailes, il se laissa glisser à la surface de l'eau. Lou fut fascinée par ce spectacle. "Est-ce toi le voleur d'yeux ?" lanca-t-elle en pensée au héron. L'oiseau s'éleva dans le ciel, et il finit par disparaître derrière la cime des arbres. 
<br></br>&nbsp;&nbsp;Il fallut à Lou quelques instants pour sortir de cette scène onirique et retrouver la réalité. Elle se décida pour retourner à son vélo. En se levant, elle essaya à nouveau de contacter Norah, mais elle n'avait toujours pas de réponse. Elle souffla, le calme qu'elle avait acquis par le vol gracieux du héron avait vite laissé place à l'agacement qu'elle éprouvait plus tôt. 
<br></br>&nbsp;&nbsp;Elle remontait le chemin vers son vélo quand elle entendit un craquement de branche non loin d'elle. Elle pensa à un animal, et tourna la tête vers l'endroit d'où provenait le son. Elle s'arrêta, ou plutôt, tout son corps se figea devant ce qu'elle entrevit derrière les feuillages plongés dans l'obscurité.
<br></br>&nbsp;&nbsp;Un oeil, rond, parfaitement rond, étrangement rond, anormalement rond, était fixé sur elle. Il était gros comme une balle de golf et légèrement jaunâtre. Il scintillait d'un éclat vif, hypnotique, menaçant. Mais le plus perturbant, c'est qu'il semblait être seul. Le coeur de Lou tambourinait dans sa cage thoracique, mais elle restait parfaitement immobile. L'oeil se trouvait à seulement quelques mètres d'elle. 
<br></br>&nbsp;&nbsp;Le cerveau de Lou était trop préoccupé à gérer l'état d'alerte qu'il avait déclenché pour analyser l'anatomie de ce qui était devant elle. Elle distinguait une forme quasiment imperceptible derrière l'oeil, quelque chose qui ressemblait à une tête, puis ombre plus importante paraissait être le corps. 
<br></br>&nbsp;&nbsp;Mais l'oeil brillait d'un scintillement si singulier dans la pénombre qu'elle ne pouvait en détourner le regard. Cet oeil la transperçait. Il émanait un force d'attraction terrifiante. Lou était terrorisée. Sa gorge était nouée, ses muscles raidis, sa peau glacée. Pourtant, elle ne pouvait s'empécher de regarder cet oeil. Il l'appelait. Tout son corps hurlait de s'enfuir, mais elle en était incapable. Pire encore, elle sentit qu'elle s'avançait contre son gré vers l'oeil. C'était plus fort qu'elle, comme si quelque chose avait pris le contrôle de son corps. Elle ne pouvait rien faire, mis à part constater avec horreur qu'elle se rapprochait de la créature terrifiante. 
<br></br>&nbsp;&nbsp;Tout à coup, il y eu un grésillement, et la voix de Norah retentit : "Lou c'est moi ! Je suis désolée mais je n'avais plus de piles. Je pars de chez moi là, tu es où toi ?" Au même instant, l'oeil se détourna vivement et la créature s'enfonça d'un coup dans les arbres et disparut. Lou sentit quelque chose dans son corps se relâcher, et dans un mouvement de panique, elle réussit à s'enfuir précipitemment vers son vélo. Elle l'enfourcha et détala plus vite que jamais. 
<br></br>&nbsp;&nbsp;Elle ne réalisait pas ce qu'elle venait de vivre. Son corps pédalait machinalement, et toute son énergie était concentrée dans ses jambes pour s'éloigner le plus possible de l'étang. Elle n'était pas encore en état de réfléchir, c'était un instinct de sauvegarde qui lui avait fait suivre le chemin vers la prairie, vers la foule, vers la multitude rassurante. Elle reprenait ses esprits peu à peu. Sa langue, qui jusqu'alors était restée collée à son palait tant son corps avait ressenti l'effroi, commença à se détendre. 
<br></br>&nbsp;&nbsp;Toujours sonnée, elle parvint à lever le <i>tolki</i>, et articula d'un ton éteint à Norah : "Je suis à côté du deuxième pont dans la prairie. Je t'attends." Elle marqua une pause, comme pour réuinir ses forces, et elle ajouta : "Norah, je crois que j'ai trouvé le voleur d'yeux."
</p>
<br></br>
    </div>)
}