export default function Chapitre4() {
    return (<div style={{maxWidth:"600px", textAlign:"justify"}}>
<h2>Chapitre 4 : L'Omniculus</h2>
<br></br>
        <p>
&nbsp;&nbsp;Margaux était arrivée peu de temps après Norah. Lou était encore sous le choc. Elle avait tout raconté à ses amies, et le fait de mettre des mots sur ce qu'elle avait éprouvé l'aida à retrouver ses esprits. Elles étaient toutes les trois effrayées par cette histoire. Norah avait tout de suite fait le rapprochement entre les animaux qui avaient perdu leurs yeux et la mystérieuse créature de l'étang.  
<br></br>&nbsp;&nbsp;Pendant que la foule qui parsemait la prairie contemplait avec émerveillement les explosions lumineuses du feu d'artifice, Lou ressentait encore la puissante attraction qui lui avait fait complètement perdre le contrôle de ses membres. Au milieu du spectacle, il y eu une fusée plus rapide que les autres qui s'élança seule dans le ciel. Elle finit sa course folle dans un éclat de lumière intense. Dans le halot lumineux où avait eu lieu l'explosion, Lou vit se dessiner un oeil qui se braqua sur elle. Les détonations des fusées devinrent lointaines, et toute l'attention de Lou était dirigée vers cet organe scintillant et rond qui restait suspendu dans le ciel noir de la nuit. Cette vision resta imprégnée sur sa rétine, et elle sentait que le regard hypnotique de la créature pesait encore sur elle. 
<br></br>&nbsp;&nbsp;Lorsque le feu d'artifice fut fini, les trois filles se dirent au revoir avec un sentiment d'inquiétude. Elles se promirent de trouver des réponses, et ce dès que possible. Norah et sa famille devaient partir le lendemain pour une semaine de vacances, et Lou partait deux jours après pour quelques jours chez sa tante en Normandie. Les deux nuits avant le départ furent difficiles. Lou ne cessait de se réveiller avec la sensation angoissante d'être observée. Heureusement, le séjour chez sa tante lui fit du bien, et bien que l'impression d'être scrutée ne l'avait pas quittée, elle se sentait plus en sécurité. 
<br></br>&nbsp;&nbsp;Une semaine s'était passée depuis la fête nationale. Les trois amies s'étaient enfin retrouvées pour discuter à tête reposée de l'évènement traumatisant qui avait eu lieu. Elles s'étaient données rendez-vous à la médiathèque de Saint-Maur.  
<br></br>&nbsp;&nbsp;Assises autour d'une table, elles essayaient de trouver la nature de la créature que Lou avait rencontrée.
<br></br>&nbsp;&nbsp;"Regardez, dit Margaux en sortant un grand livre de son sac. J'ai trouvé ça dans mon grenier." Elle ouvrit un grand ouvrage qui avait l'air de dater de l'époque de ses grands-parents, voire même de ses arrières grands-parents. C'était une encyclopédie animalière illustrée, très riche et pleine de détails anatomiques.
<br></br>&nbsp;&nbsp;"Tu penses que tu pourrais reconnaître l'oeil que tu as vu ? demanda Margaux à Lou en lui montrant des images d'yeux d'animaux.
<br></br>- Hum, peut-être, répondit Lou. Ce qui est sûr, c'est que je n'ai pas oublié à quoi il ressemble. Je le vois même en rêve. Enfin, plutôt dans mes cauchemars..." 
<br></br>&nbsp;&nbsp;Lou tourna les pages du livre jusqu'aux animaux qui peuplent sa région. Après quelques minutes d'observation, elle dit : 
<br></br>&nbsp;&nbsp;"Je ne vois aucun oeil qui ressemble à celui que j'ai vu. Je pense qu'on se trompe de piste de toute façon, fit Lou à ses amies. Ce n'était pas un animal ordinaire. Je ne sais même pas si c'était un animal. C'était une expérience, comment dire... surnaturelle, oui c'est ça, surnaturelle. Je pense qu'on doit regarder dans des livres sur les créatures surnaturelles.
<br></br>- Mais non, répondit Margaux d'un air dédaigneux, ça serait stupide.
<br></br>- Si je te demande de me citer un animal dans la nature avec qu'un seul oeil, tu saurais m'en trouver ?" lui demanda Lou. Et, n'attendant pas sa réponse, elle poursuivit : "Par contre, si je te demande de me donner une créature mythologique qui n'a qu'un seul oeil, là ça devient plus facile !"
<br></br>- Le cyclope ! s'exclama Norah. 
<br></br>- C'est ça, fit Lou en acquieçant de la tête. Mais je ne pense pas que c'en était un, c'était certainement autre chose. C'est pour ça qu'on doit chercher sans perdre de temps !"
<br></br>
<br></br>&nbsp;&nbsp;Elles se levèrent et allèrent faire un tour dans la médiathèque pour réunir tous les livres traitant de monstres, de légendes, de mythologies, de cryptozoologie et autres textes issus de l'imagination humaine. Elles passèrent toute la journée à tourner des pages, scrutant chaque légende avec une créature pourvue d'un seul oeil ou relatant de disparition d'yeux. Elles en trouvèrent, mais bien que ces histoires partageaint des similitudes avec ce qu'elles avaient vécu, aucune ne correspondait tout à fait. Ayant épuisé toute la pile de livre qu'elles avaient selectionnés, elle firent découragées. 
<br></br>&nbsp;&nbsp;"Hé ! s'écria Margaux tout à coup. On peut utiliser l'ordinateur de la médiathèque pour faire des recherches sur Internet ! Là c'est sûr qu'on va trouver." Elles se précipitèrent devant une machine et ouvrirent le navigateur. Elles commencèrent par taper les mots clés "créature à un oeil", ou encore "monstre à un oeil hypnotique", mais les résultats qui sortaient n'étaient pas très concluants.
<br></br>&nbsp;&nbsp;Puis, à force de cliquer d'un lien à un autre, elles se trouvèrent devant un site intitulé "Fondation Mondiale du Recensement des Cryptides". Ce site était un wiki, c'est à dire une grande encyclopédie en ligne, qui se décrit de la manière suivante : "La Fondation Mondiale du Recensement des Cryptides, ou FMRC, est une organisation participative dont le but est d'alimenter et maintenir une base de données recensant des créatures mystiques rencontrées à travers le monde." Par chance, il y avait la possibilité de faire des recherches avec des filtres, et notamment à partir de caractéristiques physiques de créatures. 
<br></br>&nbsp;&nbsp;Sans plus attendre, elles parcoururent la liste des créatures qui s'affichèrent après avoir gardé la caractéristique "oeil". Chaque ligne qui défilait était composée d'une image, parfois absente, représentant une créature. À côté se trouvait un nom, la plupart du temps en latin. Après quelques instants, Lou eu un frisson lorsqu'elle reconnu l'oeil sur une image qui venait d'apparaitre. "C'est ça !" s'écria-t-elle en la montrant du doigt. Margaux, qui tenait la souris, cliqua, et une page descriptive s'afficha. Norah lu à voix haute :
<br></br>&nbsp;&nbsp;"<i>Omniculus Parasitus. Région du monde : Europe et Asie. Premier recensement : XVème siècle. Description : L'Omniculus Parasitus est un être parasite qui a pour hôte les êtres humains. Il a l'apparence d'un oeil, prolongé de filaments nerveux qui lui permettent de se fixer à son hôte. Il se loge dans la bouche, en la maintenant ouverte, et prend le contrôle du corps de l'hôte en envahissant son système nerveux. Contrairement à la plupart des parasites, l'Omniculus n'a pas pour motivation l'alimentation ou la reproduction par l'intermédiaire de son hôte. L'Omniculus ne cherche qu'une chose : tout voir. Une fois qu'il a trouvé un premier hôte, il peut propager sa vision en parasitant d'autres hôtes avec des yeux, souvent provenant d'animaux, et à travers lesquels il peut se connecter pour avoir une vision ubiquitaire.</i>" Les filles faisaient une grimace en imaginant un parasite dans leur bouche. Norah poursuivit : "<i>L'Omniculus a une caractéristique propre, qui est le regard persuasif. Son oeil possède une force d'attraction puissante, capable de prendre le contrôle d'une personne afin de l'attirer vers lui, dans le but d'en faire un nouvel hôte. L'Omniculus est très dangereux, et il est nécessaire de l'arrêter le plus tôt possible avant qu'il n'infecte trop de personnes.</i>"
<br></br>&nbsp;&nbsp;Norah se tut, et les trois filles échangèrent un regard plein d'effroi.
<br></br>&nbsp;&nbsp;"Tout concorde !" s'exclama Lou. "Les yeux des animaux morts, ce que j'ai vu le soir de la fête nationale, le regard persuasif... L'Omniculus, voilà donc à quoi on a à faire. Mais comment il est apparut ? Et surtout, comment on va faire pour s'en débarasser ?
<br></br>- Comment ça <i>on</i> ? fit Norah avec inquiétude. On doit prévenir les parents, la police, l'armée ! Tu as entendu ? L'Omniculus est très dan-ge-reux !
<br></br>- Bien sûr que j'ai entendu, répondit Lou, mais ça dit aussi qu'il faut l'arrêter le plus tôt possible ! Tu imagines le temps qu'on va perdre à devoir leur expliquer tout ce qu'on a vu ? Et tu penses qu'ils vont nous croire aussi facilement ? Non, il vaut mieux qu'on agisse nous même avant que l'Omniculus ne fasse de nouvelles victimes. 
<br></br>- Je suis d'accord avec toi Lou, fit Margaux d'un ton résigné. 
<br></br>- Et comment tu comptes t'y prendre, demanda Norah toujours inquiète. 
<br></br>- On doit monter un plan, répondit Lou."
<br></br>&nbsp;&nbsp;"On va fermer !" lança une bibliothéquère à leur attention. 
<br></br>&nbsp;&nbsp;"On voit ça demain, fit Margaux en lança un clin d'oeil à Lou". Le lendemain, elles se retrouvaient pour l'anniversaire de Lou. 

        </p>
        
<br></br>
    </div>

    )
}