export default function Chapitre1() {
    return (<div style={{maxWidth:"600px", textAlign:"justify"}}>
<h2>Chapitre 1 : L'évadé</h2>
<br></br>
<p>&nbsp;&nbsp;L'été semblait avoir commencé depuis deux mois déjà dans la petite commune de Saint-Maur, bien que ce ne fut que les premiers jours de juillet. Depuis la fin du mois de mai, la chaleur alourdissait l'air jusque dans les maisons. Pour faire face à cet ennemi omniprésent, Lou, Margaux et Norah s'étaient retrouvées autour du barrage pour se baigner dans la rivière.</p>
<p>&nbsp;&nbsp;Juste à coté du barrage, sur la berge, se trouvait un grand arbre auquel étaient clouées des planches pour pouvoir y grimper. Margaux était la première a avoir escaladé l'échelle de fortune et elle se tenait debout sur une grosse branche, prête à sauter. En s'assurant à chaque mouvement que rien n'allait casser, Lou la rejoignait avec prudence. Margaux, ainsi perchée, lança à leur troisième amie restée en bas : "Norah ! Monte avec nous, on va sauter !"</p>
<p>&nbsp;&nbsp;Norah était accroupie à coté des vélos et cherchait quelque chose dans son sac. En entendant Margaux, elle releva la tête en soulevant son chapeau pour pouvoir la voir, et, fronçant les sourcils à cause de la luminosité, lui répondit :</p>
<p>&nbsp;&nbsp;"Je ne trouve pas ma crème solaire, pas question pour moi d'aller dans l'eau. J'irai peut-être me tremper les pieds, mais je veux rester à l'ombre.</p>
<p>- Mais si viens avec nous , tu ne vas quand même pas ne pas te baigner alors qu'il fait super chaud ! lui cria Lou qui avait rejoint son amie sur la branche.</p>
<p>- Je ne vais quand même pas attraper des coups de soleil le premier jour des vacances !  répondit Norah.</p>
<p>- Tant pis pour toi, s'exclama Lou avec un air malicieux."</p>
<p>&nbsp;&nbsp;Il y eu un grand bruit de plongeon : Margaux avait sauté. Elle alla retrouver Norah restée sous l'arbre.</p>
<p>&nbsp;&nbsp;Seule sur la branche, Lou se pencha légèrement pour examiner l'eau dans laquelle elle s’apprêtait à plonger. Bien qu'un peu vaseuse, ce n'était pas tant la propreté de la rivière que sa profondeur qui l'interrogeait. Puis elle repensa à Margaux qui venait de sauter sans encombre, et elle se dit que ce ne devait pas être dangereux.</p>
<p>&nbsp;&nbsp;Cependant, au moment même où elle s'apprêtait à basculer en avant, elle s'arrêta. Ses deux amies l'observaient d'en bas, et Margaux s'écria d'un ton railleur : "Et bah alors Lou, tu as la frousse ?"</p>
<p>&nbsp;&nbsp;Lou, les yeux fixés vers l'eau, faisait une grimace. Une pensée avait traversé son esprit. Sa mère, dont l'inquiétude parentale saine se voyait souvent amplifiée par des articles discutables trouvés en ligne, l'avait mise en garde face aux vers parasites qui croupiraient dans les cours d'eau. Ces vermines font occasionnellement l'actualité après avoir provoqué la mort de leur hôte infortuné dans des conditions tristement spectaculaires. Lou s'était rappelée de cette information désagréable alors qu'elle allait sauter et elle s'était ravisée, dégoûtée à l'idée qu'un organisme indésirable et funeste loge en elle.</p>
<p>&nbsp;&nbsp;"Tu veux passer tout l'après-midi sur la branche ?" lança Norah. Ne voulant pas passer pour une dégonflée, Lou se laissa tomber dans l'eau un peu malgré elle. Elle se dépêcha de retrouver ses amies sur la berge, en prenant soin de ne pas avaler la moindre goutte. Arrivée au sec, elle leur expliqua la crainte qui s'était introduite dans son esprit.</p>
<p>&nbsp;&nbsp;"Oh mais ne t'en fais pas, lui répondit Norah, ces bestioles ne vivent que dans des eaux très polluées. La station d'épuration est un peu plus haut, et mon papa dit que l'eau qui en sort et très propre." Elle disait tout cela avec simplicité et assurance, si bien que Lou se trouva quelque peu rassurée.</p>
<p>&nbsp;&nbsp;Margaux parla a son tour et décrivit des champignons parasites qui prenaient le contrôle d'escargot qu'elle avait vu dans son magazine hebdomadaire. Leur conversation se poursuivit et bifurqua vers leur professeur de SVT, puis celle de musique, puis elle reparlèrent d’anecdotes du collège, et ainsi de suite. Leur après-midi passa en un éclair et elle rentrèrent chacune chez elles bien fatiguées, après s'être donné rendez-vous au même endroit le lendemain.</p>
<br></br>

<p>&nbsp;&nbsp;Le jour suivant, Norah et Margaux se trouvaient déjà à côté du barrage quand Lou arriva à toute allure sur son vélo. Elle freina sèchement et repoussa vite sa monture pour se saisir de son sac à dos. Un grand sourire au lèvres, elle en sorti des petits boîtiers rouges et noirs. "Regardez ce que j'ai ramené !" Ses deux amies l'observèrent d'un air curieux.</p>
<p>&nbsp;&nbsp;"Qu'est-ce que c'est ? demanda Norah.</p>
<p>- Des <i>tolkiwokis</i> ! s'écria Lou avec enthousiasme. Elle ne connaissait le mot <i>talkie-walkie</i> qu'oralement, si bien qu'elle le prononçait en compressant les syllabes. Je les ai piqués à mon grand frère, dit elle fièrement. Apparemment, ça a une portée de dix kilomètres ! On pourra se parler même en étant chacune chez nous. Mais attention, ils fonctionnent avec des piles, et il faudra s'en servir qu'en cas d'urgence pour ne pas user la batterie."</p>
<p>Les deux petites s'étaient saisi des appareils et les manipulaient avec intérêt. Après avoir pressé tous les boutons, elles parvinrent à faire entendre leur voix grésillante d'un <i>toki</i> à l'autre. Elles réalisèrent tout le potentiel ludique de ces petits gadgets et commencèrent à faire des bruits onomatopéiques qui les faisaient bien rire. "Ça suffit !" Lou saisis les deux <i>tolkiwolkies</i> des mains de ses camarades. "Je vous ai dit qu'on s'en servira qu'en cas d'urgence, et qu'en attendant, il faut préserver les piles.</p>
<p>- Mais nous sommes en cas d'urgence, lui rétorqua Margaux, mécontente d'avoir été coupée dans son moment d'amusement.</p>
<p>- Comment ça ? demanda Lou.</p>
<p>- C'est ce que je racontait à Margaux avant que tu arrives, commença Norah. Mon papa a des amis d'amis qui travaillent à la centrale, et apparemment, il y aurait eu une évasion la nuit dernière. C'est pas cent pour cent sûr, mais c'est tout de même peu rassurant."</p>
<p>&nbsp;&nbsp;La maison centrale était un établissement carcéral de la commune, non loin du quartier de Bel-Air où habitait Norah. Cet établissement était réputé pour accueillir des criminels de "haut calibre", comme avait dit le père de Norah lorsqu'il lui avait expliqué ce qu'il avait entendu dire par ses amis. Le fait que ce n'était pas une prison ordinaire, de par la dangerosité de ses détenus, rendait cette potentielle évasion d'autant plus inquiétante.</p>
<p>&nbsp;&nbsp;"Combien de prisonniers se sont échappés ? demanda Lou.</p>
<p>- Mon papa ne m'a parlé que d'une personne, mais on n'a pas tous les détails. On ne sait même pas comment ça a été possible, c'est la première fois que ça arrive ! répondit Norah.</p>
<p>- Ça veut dire qu'un dangereux criminel est en liberté dans Saint-Maur, s'inquiéta Margaux.</p>
<p>- Il a sûrement pris la fuite pour s'éloigner le plus possible de la prison, suggéra Lou. </p>
<p>- Peut-être, fit Norah, mais dans tous les cas mon papa m'a demandé de rentrer pour le goûter car il ne veut pas que je reste trop longtemps dehors. J'ai bien peur qu'il refuse de me laisser sortir tant que l'évadé n'a pas été retrouvé...</p>
<p>- Oh non ! s'exclama Margaux. Pourquoi ça arrive au début de l'été et pas pendant l'école...</p>
<p>- Bon, dit Lou d'un ton sérieux, si jamais nos parents nous obligeaient à rester chacune à la maison, on pourra quand même communiquer, dit elle en montrant les <i>tolkiwolkies</i> qu'elle tendit à ses amies."</p>
<p>&nbsp;&nbsp;Elles prirent chacune cette maigre consolation face à la situation qui menaçait de faire basculer un été chargé d'explorations et d'aventures dans des vacances à domicile, mêlées d'ennui et d'inquiétude. 
Leur après-midi se déroula comme hier, entre les jeux d'eau et les discussions animées, mais l'atmosphère, déjà rendue lourde par la chaleur, était encore plus pesante. L'idée qu'un criminel était en liberté dans les parages, et que leurs vacances en étaient altérées, gâcha un peu le plaisir qu'elles éprouvèrent cette journée là. Elles rentrèrent toutes les trois chez elles pour l'heure du goûter.</p>
<p>&nbsp;&nbsp;Comme elles l'avaient craint, la nouvelle de l'évadé se confirma et tous les parents étaient au courant dans la soirée. Il fut hors de question de se sortir retrouver ses copines tant que la police ne l'aura pas retrouvé. Les deux jours suivants, elles furent assignées à domicile, et arriva le premier week-end de leurs vacances, sans que la police n'eu obtenu de piste pour retrouver l'évadé.</p>
<br></br>
    </div>)
}